### ISSUE TITLE
Notification language problem

### ISSUE THREAD

**Issue by benda95280** [DevBobcorn/CornCraft#9] opened 2024-05-17 11:43 UTC
Dear,

The notification is not showing any language :
![image](https://github.com/DevBobcorn/CornCraft/assets/1539408/2b8b8b44-dc56-464e-aaa9-095dc6bb6282)

Any idea ?
Thanks

**Comment by DevBobcorn** [comment] 2024-05-17 12:31
The data loader is still under development and will be available soon, but before that it will require some manual set up to properly load the resource and data files(including translation files). I'll leave a reply here when I complete this.

**Comment by DevBobcorn** [comment] 2024-05-17 12:34
Duplicate of #8 .

**Closed** 2024-05-17 12:34 UTC
